version: '3.5'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
      target: development
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=video_sharing
    ports:
      - '5433:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis:/data
  redis-gui:
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8082:8081'
    depends_on:
      - redis

volumes:
  redis:
    driver: local
  docker-nest-postgres:
    driver: local
